name: Raspador de Noticias Diario

on:
  workflow_dispatch:
  schedule:
    - cron: '45 4 * * *'

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. (NUEVO) Instalar Google Chrome para Selenium
      # Este paso descarga e instala una versión de Chrome compatible en el runner
      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@latest

      # 4. Instala las dependencias de Python (incluyendo selenium)
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Ejecuta el script con Selenium
      - name: Ejecutar el script de scraping y notificación
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python main.py
