name: Raspador de Noticias Diario

on:
  workflow_dispatch:
  schedule:
    - cron: '45 4 * * *'

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar el script de scraping y notificación
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          # --- AÑADIMOS EL NUEVO SECRETO DEL PROXY ---
          PROXY_ES: ${{ secrets.PROXY_ES }}
        run: python main.py
