
name: Resumen Diario de Noticias

on:
  # Permite ejecutar este workflow manualmente desde la pestaña Actions de GitHub
  workflow_dispatch:

  # Define la ejecución programada
  schedule:
    # Se ejecuta todos los días a las 08:00 UTC (puedes ajustar la hora)
    # Formato: minuto hora día mes día_de_la_semana
    - cron: '0 8 * * *'

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu repositorio para tener acceso al script
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Usamos una versión estable de Python

      # 3. Instala las librerías necesarias para el script
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests

      # 4. Ejecuta el script de noticias
      - name: Run news aggregator script
        env:
          # Pasa el secreto que configuraste al entorno del script
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: python agregador_noticias.py
